services:
  postgres:
    image: postgres:18
    container_name: raumi-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: raumi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgresql:/var/lib/postgresql
